### ISSUE TITLE
Implement the Builder API

### ISSUE THREAD

**Issue by agalbachicar** [maliput/maliput_sparse#10]
## Desired behavior

Propose a Builder API to build a RoadGeometry. It should be used to generate RoadGeometries at build time via programatic descriptions or used by parsers of specific map formats, such as lanelets or OSM.

## Victory condition

Define and implement the builder API that allows to build a RoadGeometry.

**Comment by francocipollone** [comment]
One comment that could affect Builder API and its implementation.

The process of the programmatically creating the road geometry can be approached via different ways:
 - 1. Building lanes as they are added to the RoadGeometry. Which would allows to have intermediate states of the road geometry as it is built.
 - 2. Adding all the instructions for the creation of the road geometry and then running the process of building it. 
     Like:
     ```cpp
     ...
     ...
     RoadGeometryDiagram rg_diagram;
     Lane lane_a{id, line_string_a, line_string_b};
     rg_diagram.AddLane(lane_a)
     ...
     ...
     auto rg = RoadGeometryBuilder(rg_diagram);
     ```
 I found the latter a better approach as the process of building would be easier and straight forward as the Lanes don't have to change their information about connections when new lanes are added because the diagram will have that information already. Also, parallelizing the building could be done to minimize the time of building.
