### ISSUE TITLE
Implement Lane class.

### ISSUE THREAD

**Issue by francocipollone** [maliput/maliput_sparse#15]
### Summary

Implement Lane class that inherits from maliput::geometry_base::Lane class with the help of LaneGeometry class #7 

### To Implement

maliput::api::Lane virtual methods should be here implemented:

```cpp
  double do_length() const override { return length_; }
  maliput::api::RBounds do_lane_bounds(double s) const override;
  maliput::api::RBounds do_segment_bounds(double s) const override;
  maliput::api::HBounds do_elevation_bounds(double, double) const override { return elevation_bounds_; }
  maliput::math::Vector3 DoToBackendPosition(const maliput::api::LanePosition& lane_pos) const override;
  void DoToLanePositionBackend(const maliput::math::Vector3& backend_pos, maliput::api::LanePosition* lane_position,
                               maliput::math::Vector3* nearest_backend_pos, double* distance) const override;
  maliput::api::Rotation DoGetOrientation(const maliput::api::LanePosition& lane_pos) const override;
  maliput::api::LanePosition DoEvalMotionDerivatives(const maliput::api::LanePosition& position,
                                                     const maliput::api::IsoLaneVelocity& velocity) const override;
```

**Comment by francocipollone** [comment]
Regarding the computation of
```cpp
maliput::api::RBounds do_lane_bounds(double s) const
```

![image](https://user-images.githubusercontent.com/53065142/189693834-7a65bfe1-dfee-4128-a6dc-7204131bf50f.png)
Note: Red line is the centerline.

For finding `r_max` and `r_min` in order to compute the lane bounds we should find the points in the left and right line string that would match to an equivalent p in the centerline. Once we have those points we can get the distance to the centerline and then simply obtain the `r_min` and `r_max`.

At first I thought finding those points as the minimum distance from P in the centerline however it only works for parallel lines,(when width isn't changing).


An alternative is to obtain the point that interesects the ` r_vector` with the left / right line string and from there compute the boundaries.

Do you see other alternatives or recomendations? @agalbachicar

**Comment by francocipollone** [comment]
I'd like to get your input on this matter @agalbachicar

**Comment by agalbachicar** [comment]
For the record, @francocipollone and I met to review this. We decided that we had to work on superelevation as well because the orientation affects where on the left and right lane borders we would intersect to compute the lane boundaries or the segment boundaries.
In addition, it is worth noting that from the centerline to the left and from the centerline to the right, we might find two different roll angles due to the nature of the algorith computing the centerline. That said, it is convenient sticking to the generated planes and not creating another derived superelevation angle from the available geometry. With this in mind, we decided to proceed the following way:

- When computing the orientation on the surface, we will create 2 ranges: `[-r_min; 0)` and `[0; r_max]`. When `r < 0.`, the orientation will be computed in the plane generated between the centerline and the towards `-r_min` linestring. Otherwise, the centerline and the towards `r_max` linestring will be used.
- To compute the orientation on a plane we will proceed this way:
  - Given `p` in centerline, compute `p_at_a_border` (border could be the right or left linestring given the previous consideration) as: `p_at_a_border = p / length * length_at_a_border`.
  - Create a line between the inertial coordinates of the centerline evaluated at `p` --> `x_p` and the border line evaluated at `p_at_a_border` --> `x_b`. From that line:
    - The lateral boundary distance is `| x_p - x_b |`
    - The orientation vector is defined by `( x_p - x_b ) / | x_p - x_b |` in that direction. Note that this one should not be used to compute `r_hat` though. 

This procedure has some flaws:
- It does not produce normal vectors, i.e. `r_hat` as it is not normal to `s_hat` in the general case. In case `r_hat` is desired, it must be derived from the normal plane:
  - Let `N` be plane defined by a point and a normal vector to that point such that `x_p` is the point and `s_p` is the normal vector.
  - Compute the inertial frame point `x_b` following the previous procedure and a tangent vector `s_b`.
  - We want to compute the intersection of the line `B: x_b + p_at_a_border * s_b` with the plane `N` which yields a point `x_b_N`, such `<s_p, x_b + p_at_a_border * s_b - x_p> = 0`. Derive `p_b_N = ( <s_p, x_b > - <s_p, x_b> ) / (<s_p, s_b> )` wich is the parameter of the border that allows to compute `x_b_N`. This process is also not that simple and might require iteration due to the polyline nature of the border curve.

**Comment by francocipollone** [comment]
Some pendings are tackled at #31
